[pack]
__title = "Configuration"
name = "string(default='example-pack')"
name__title = "Pack Name"
source_path = "string(default='./src')"
source_path__title = "Resourcepack sources"
output_path = "string(default='./resourcepacks')"
output_path__title = "Output directory"
license_path = "string(default=None)"
license_path__title = "License file"
allowed_paths = "list(default=list('assets/', 'pack.mcmeta', 'pack.png'))"
allowed_paths__title = "Allowed paths"
future_compatibility = "integer(min=1, max=500, default=25)"
future_compatibility__title = "Future compatibility"

[optimize]
__parent = "pack"
__title = "Optimize files:"
png = "boolean(default=false)"
png__title = "│ PNG"
json = "boolean(default=false)"
json__title = "│ JSON"
mcmeta = "boolean(default=false)"
mcmeta__title = "│ MCMETA"

[theming]
__title = "Pack theming"
enabled = "boolean(default=false)"
enabled__title = "Theming enabled"
theme_dir = "string(default='./themes')"
[[colormap]]
__parent = "theming"
primary = "string(default='#ffffff')"
secondary = "string(default='#ffffff')"
accent = "string(default='#ffffff')"
background = "string(default='#ffffff')"

[svg2png]
__parent = "pack"
__toggle = "svg2png.enabled"
enabled = "boolean(default=false)"
enabled__title = "SVG processing"
[[scales]]
__parent = "pack"
__toggle = "svg2png.enabled"
__title = "Scales"
__type = "list_values"
2 = "integer(1, 500, default=48)"
3 = "integer(1, 500, default=72)"
4 = "integer(1, 500, default=96)"

[formats]
__ignore = true
# Format configuration is to be reworked
